<?xml version="1.0" ?>
<robot name="k9_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- ===================== Materials ===================== -->
  <material name="K9_grey">
    <!-- NOTE: the model is largely transparent in RViz -->
    <color rgba="0.25 0.25 0.25 1.0" />
  </material>

  <material name="perspex_red">
    <color rgba="1.0 0.1 0.1 1.0" />
  </material>

  <material name="wheel_grey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <!-- ===================== Robot constants ===================== -->
  <!-- Chassis dims (m) -->
  <xacro:property name="base_width"  value="0.49"/>
  <xacro:property name="base_length" value="0.81"/>
  <xacro:property name="base_height" value="0.52"/>

  <!-- Drive wheels (m) -->
  <xacro:property name="wheel_radius" value="0.06939"/>
  <xacro:property name="wheel_width"  value="0.025"/>

  <!-- Wheel center-to-center separation (m) -->
  <xacro:property name="track" value="0.2022"/>

  <!-- Wheel x offset relative to base_link -->
  <xacro:property name="wheel_xoff" value="0.0"/>

  <!-- Caster configuration -->
  <xacro:property name="castor_xoff" value="-0.298"/>

  <!-- 40 mm caster wheel -->
  <xacro:property name="caster_wheel_radius" value="0.02"/>
  <xacro:property name="caster_wheel_width"  value="0.012"/>
  <xacro:property name="caster_fork_offset"  value="0.018"/>  <!-- axle behind swivel -->

  <xacro:property name="caster_mount_x" value="${castor_xoff}"/>
  <xacro:property name="caster_mount_y" value="0.0"/>
  <!-- base_link is at axle height; place swivel so wheel touches ground -->
  <xacro:property name="caster_mount_z" value="${-wheel_radius + caster_wheel_radius -0.002}"/>

  <!-- ===================== Inertia helper macros ===================== -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia
        ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0"
        iyy="${(m/12) * (w*w + d*d)}" iyz="0.0"
        izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia
        ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0"
        iyy="${(m/12) * (3*r*r + h*h)}" iyz="0"
        izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- Simple “tiny inertial” for fixed-mounted accessories to keep Gazebo happy -->
  <xacro:macro name="tiny_inertial" params="m i">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia ixx="${i}" ixy="0" ixz="0" iyy="${i}" iyz="0" izz="${i}"/>
    </inertial>
  </xacro:macro>

  <!-- ===================== Base frames ===================== -->
  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <origin xyz="-0.5 1.905 0" rpy="0 0 ${pi}"/>
      <geometry>
        <mesh filename="file:///home/hopkira/Documents/GitHub/k9-gazebo/src/k9_description/urdf/k9.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="K9_grey"/>
    </visual>

    <!-- Collision layout avoids wheels and mirrors head/body -->
    <collision>
      <origin xyz="-0.119 0.0 0.285" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.89 0.49 0.49"/>
      </geometry>
    </collision>

    <collision>
      <origin xyz="0.336 0.0 0.6125" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.43 0.18 0.295"/>
      </geometry>
    </collision>

    <inertial>
      <!-- Shift COM slightly behind wheel contact line to prevent nose tipping -->
      <origin xyz="-0.02 0 0.15" rpy="0 0 0"/>
      <mass value="25.0"/>
      <inertia
        ixx="0.98230"  ixy="0.0"  ixz="0.0"
        iyy="2.4"  iyz="0.0"
        izz="2.03021"/>
    </inertial>

  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ===================== Drive wheels ===================== -->
  <xacro:macro name="wheel" params="prefix x y">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="wheel_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_footprint"/>
      <child link="${prefix}_link"/>
      <!-- wheel center is wheel_radius above ground -->
      <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.05" friction="0.0"/>
    </joint>

  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l" x="${wheel_xoff}" y="${ track/2}" />
  <xacro:wheel prefix="drivewhl_r" x="${wheel_xoff}" y="${-track/2}" />

  <!-- ===================== Swivel caster ===================== -->
  <link name="caster_swivel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.008" length="0.03"/>
      </geometry>
      <material name="wheel_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.008" length="0.03"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.15" r="0.008" h="0.03"/>
  </link>

  <joint name="caster_swivel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="caster_swivel_link"/>
    <origin xyz="${caster_mount_x} ${caster_mount_y} ${caster_mount_z}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.8" friction="0.0"/>
  </joint>

  <link name="caster_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_width}"/>
      </geometry>
      <material name="wheel_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.10" r="${caster_wheel_radius}" h="${caster_wheel_width}"/>
  </link>

  <joint name="caster_wheel_joint" type="continuous">
    <parent link="caster_swivel_link"/>
    <child link="caster_wheel_link"/>
    <origin xyz="${-caster_fork_offset} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.10" friction="0.0"/>
  </joint>

  <!-- ===================== Sensors / accessories (with inertials) ===================== -->
  <link name="lidar_link">
    <xacro:tiny_inertial m="0.05" i="1e-5"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="-0.112 0.0 0.565" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="eyecam_link">
    <xacro:tiny_inertial m="0.05" i="1e-5"/>
  </link>

  <joint name="eyecam_joint" type="fixed">
    <parent link="base_link"/>
    <child link="eyecam_link"/>
    <origin xyz="0.366 0.0 0.67" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="3dcam_link">
    <xacro:tiny_inertial m="0.10" i="2e-5"/>
  </link>

  <joint name="3dcam_joint" type="fixed">
    <parent link="base_link"/>
    <child link="3dcam_link"/>
    <origin xyz="0.206 0.0 0.255" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="l_ear_link">
    <xacro:tiny_inertial m="0.02" i="5e-6"/>
  </link>

  <joint name="l_ear_joint" type="fixed">
    <parent link="base_link"/>
    <child link="l_ear_link"/>
    <origin xyz="0.35 0.045 0.725" rpy="0.0 0.65 0.0"/>
  </joint>

  <link name="r_ear_link">
    <xacro:tiny_inertial m="0.02" i="5e-6"/>
  </link>

  <joint name="r_ear_joint" type="fixed">
    <parent link="base_link"/>
    <child link="r_ear_link"/>
    <origin xyz="0.35 -0.045 0.725" rpy="0.0 0.65 0.0"/>
  </joint>

  <!-- ===================== Gazebo Sim extensions ===================== -->

  <!-- Wheel / caster contact: give the drive wheels explicit friction too -->
  <gazebo reference="drivewhl_l_link">
    <surface>
      <friction>
        <ode>
          <mu>1.1</mu>
          <mu2>0.9</mu2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <gazebo reference="drivewhl_r_link">
    <surface>
      <friction>
        <ode>
          <mu>1.1</mu>
          <mu2>0.9</mu2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <gazebo reference="caster_wheel_link">
    <surface>
      <friction>
        <ode>
          <mu>0.3</mu>
          <mu2>0.15</mu2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <!-- Gazebo Sim diff-drive system plugin
       NOTE: This plugin consumes /cmd_vel on Gazebo Transport.
       In ROS 2 you typically bridge geometry_msgs/Twist <-> gz.msgs.Twist on /cmd_vel. -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>drivewhl_l_joint</left_joint>
      <right_joint>drivewhl_r_joint</right_joint>

      <wheel_separation>${track}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <!-- Publish gz odom + tf (bridge if you want ROS topics) -->
      <odom_publish_frequency>50</odom_publish_frequency>

      <!-- Use simple top-level topics to make bridging easy -->
      <topic>/cmd_vel</topic>
      <odom_topic>/odom</odom_topic>
      <tf_topic>/tf</tf_topic>

      <!-- Frame ids inside the gz odometry message -->
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
    </plugin>
  </gazebo>

</robot>