<?xml version="1.0"?>
<robot name="k9_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- ===================================================== -->
  <!-- Materials                                             -->
  <!-- ===================================================== -->
  <material name="K9_grey">
<<<<<<< HEAD
    <color rgba="0.25 0.25 0.25 1.0" />
  </material>

  <material name="perspex_red">
    <color rgba="1.0 0.1 0.1 1.0" />
=======
    <color rgba="0.25 0.25 0.25 1.0"/>
>>>>>>> b2d86b1 (Fixing URDF)
  </material>

  <material name="wheel_grey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

<<<<<<< HEAD
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <xacro:property name="pi" value="3.141592653589793"/>

  <!-- ===================== Robot constants ===================== -->
  <!-- Chassis dims (m) -->
  <xacro:property name="base_width"  value="0.49"/>
  <xacro:property name="base_length" value="0.81"/>
  <xacro:property name="base_height" value="0.52"/>

  <!-- Drive wheels (m) -->
  <xacro:property name="wheel_radius" value="0.06939"/>
=======
  <!-- ===================================================== -->
  <!-- Constants                                             -->
  <!-- ===================================================== -->
  <xacro:property name="wheel_radius" value="0.0694"/>
>>>>>>> b2d86b1 (Fixing URDF)
  <xacro:property name="wheel_width"  value="0.025"/>
  <xacro:property name="track"         value="0.2022"/>

  <!-- Ball caster -->
  <xacro:property name="ball_radius"  value="0.04"/>
  <xacro:property name="ball_x"       value="-0.30"/>

  <!-- ===================================================== -->
  <!-- Helper macros                                         -->
  <!-- ===================================================== -->
  <xacro:macro name="tiny_inertial" params="m">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${m}"/>
      <inertia
        ixx="1e-4" ixy="0" ixz="0"
        iyy="1e-4" iyz="0"
        izz="1e-4"/>
    </inertial>
  </xacro:macro>

<<<<<<< HEAD
  <!-- Cylinder inertia about its own center.
      rpy must match the cylinder geometry orientation -->
  <xacro:macro name="cylinder_inertia" params="m r h rpy:='0 0 0'">
    <inertial>
      <origin xyz="0 0 0" rpy="${rpy}"/>
      <mass value="${m}"/>
      <inertia
        ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0"
        iyy="${(m/12) * (3*r*r + h*h)}" iyz="0"
        izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- Simple “tiny inertial” for fixed-mounted accessories to keep Gazebo happy -->
  <xacro:macro name="tiny_inertial" params="m i">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia ixx="${i}" ixy="0" ixz="0" iyy="${i}" iyz="0" izz="${i}"/>
    </inertial>
  </xacro:macro>

  <!-- ===================== Base frames ===================== -->
=======
  <!-- ===================================================== -->
  <!-- Frames                                                -->
  <!-- ===================================================== -->
>>>>>>> b2d86b1 (Fixing URDF)
  <link name="base_footprint"/>

  <!-- ===================================================== -->
  <!-- Base / chassis                                        -->
  <!-- ===================================================== -->
  <link name="base_link">

    <!-- Visual -->
    <visual>
      <origin xyz="-0.5 1.905 ${-wheel_radius}" rpy="0 0 ${pi}"/>
      <geometry>
        <mesh filename="file:///home/hopkira/Documents/GitHub/k9-gazebo/src/k9_description/urdf/k9.stl"
              scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="K9_grey"/>
    </visual>

    <!-- Collision -->
    <collision>
      <origin xyz="0.0 0.0 0.44"/>
      <geometry>
        <box size="1.05 0.49 0.74"/>
      </geometry>
    </collision>

    <!-- Inertia: main shell + structure -->
    <!-- CHANGED: lower + slightly rear-shift COM, and increase pitch inertia (iyy) -->
    <inertial>
<<<<<<< HEAD
      <!-- Recomputed from 5 internal mass boxes (total 25.0 kg).
          Origin is COM expressed in base_link frame. -->
      <origin xyz="-0.090992 0 0.177274" rpy="0 0 0"/>
      <mass value="25.0"/>
      <inertia
        ixx="1.175508"  ixy="0.0"      ixz="-0.512311"
        iyy="2.263333"  iyz="0.0"
        izz="1.639449"/>
=======
      <!-- was: -0.02 0 0.20 -->
      <origin xyz="-0.06 0 0.16"/>
      <mass value="19.0"/>
      <inertia
        ixx="0.80"
        ixy="0" ixz="0"
        iyy="2.40"
        iyz="0"
        izz="1.70"/>
>>>>>>> b2d86b1 (Fixing URDF)
    </inertial>

  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}"/>
  </joint>

  <!-- ===================================================== -->
  <!-- Battery (low + central)                               -->
  <!-- ===================================================== -->
  <link name="battery_link">
    <collision>
      <geometry>
        <box size="0.25 0.20 0.25"/>
      </geometry>
    </collision>
    <xacro:tiny_inertial m="5.0"/>
  </link>

  <joint name="battery_joint" type="fixed">
    <parent link="base_link"/>
    <child link="battery_link"/>
    <origin xyz="0 0 0.18"/>
  </joint>

  <!-- ===================================================== -->
  <!-- Motors                                                -->
  <!-- ===================================================== -->
  <link name="motors_link">
    <collision>
      <geometry>
        <box size="0.20 0.20 0.10"/>
      </geometry>
    </collision>
    <xacro:tiny_inertial m="3.0"/>
  </link>

  <joint name="motors_joint" type="fixed">
    <parent link="base_link"/>
    <child link="motors_link"/>
    <origin xyz="0 0 0.10"/>
  </joint>

  <!-- ===================================================== -->
  <!-- Drive wheels                                          -->
  <!-- ===================================================== -->
  <xacro:macro name="drive_wheel" params="name y">
    <link name="${name}_link">
      <visual>
        <origin rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="wheel_grey"/>
      </visual>
      <collision>
        <origin rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <!-- NEW: slightly reduced friction to reduce "trip" under hard braking -->
        <surface>
          <friction>
            <ode>
              <mu>0.9</mu>
              <mu2>0.7</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
<<<<<<< HEAD
      <xacro:cylinder_inertia
        m="1.0"
        r="${wheel_radius}"
        h="${wheel_width}"
        rpy="${pi/2} 0 0"/>
=======
      <inertial>
        <mass value="1.0"/>
        <inertia
          ixx="0.002" ixy="0" ixz="0"
          iyy="0.002" iyz="0"
          izz="0.004"/>
      </inertial>
>>>>>>> b2d86b1 (Fixing URDF)
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="0 ${y} 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.05"/>
    </joint>
  </xacro:macro>

  <xacro:drive_wheel name="drivewhl_l" y="${ track/2}"/>
  <xacro:drive_wheel name="drivewhl_r" y="${-track/2}"/>

  <!-- ===================================================== -->
  <!-- Ball caster (4 cm sphere)                              -->
  <!-- ===================================================== -->
  <link name="ball_caster_link">
    <visual>
      <geometry>
        <sphere radius="${ball_radius}"/>
      </geometry>
      <material name="wheel_grey"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${ball_radius}"/>
      </geometry>
      <!-- NEW: low friction so it supports but doesn't brake/steer the robot -->
      <surface>
        <friction>
          <ode>
            <mu>0.2</mu>
            <mu2>0.2</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <xacro:tiny_inertial m="0.5"/>
  </link>

<<<<<<< HEAD
  <joint name="caster_swivel_joint" type="continuous">
    <parent link="base_footprint"/>
    <child link="caster_swivel_link"/>
    <!-- caster_mount_z is already defined relative to axle height;
        convert to base_footprint by adding wheel_radius -->
    <origin xyz="${caster_mount_x} ${caster_mount_y} ${caster_mount_z + wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.8" friction="0.0"/>
  </joint>

  <link name="caster_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_width}"/>
      </geometry>
      <material name="wheel_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia
      m="0.10"
      r="${caster_wheel_radius}"
      h="${caster_wheel_width}"
      rpy="${pi/2} 0 0"/>
  </link>

  <joint name="caster_wheel_joint" type="continuous">
    <parent link="caster_swivel_link"/>
    <child link="caster_wheel_link"/>
    <origin xyz="${-caster_fork_offset} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.10" friction="0.0"/>
  </joint>

  <!-- ===================== Sensors / accessories (with inertials) ===================== -->
  <link name="lidar_link">
    <xacro:tiny_inertial m="0.05" i="1e-5"/>
  </link>

  <joint name="lidar_joint" type="fixed">
=======
  <joint name="ball_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="ball_caster_link"/>
    <origin xyz="${ball_x} 0 ${ball_radius - wheel_radius}"/>
  </joint>

  <!-- ===================================================== -->
  <!-- Sensors                                               -->
  <!-- ===================================================== -->
  <!-- started at 0.565 raised by 20 cm to clear body       -->
  
  <link name="base_laser"><xacro:tiny_inertial m="0.05"/></link>
  <joint name="base_laser_joint" type="fixed">
>>>>>>> b2d86b1 (Fixing URDF)
    <parent link="base_link"/>
    <child link="base_laser"/>
    <origin xyz="-0.112 0 0.53" rpy ="0 0 0"/>
  </joint>
  <gazebo reference="base_laser">
    <sensor name="ld06_lidar" type="gpu_lidar">
      <update_rate>10</update_rate>
      <always_on>true</always_on>
      <topic>/world/empty/model/k9_robot/ld06/scan</topic>
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.02</min>
          <max>12.0</max>
        </range>
      </lidar>
      <always_on>true</always_on>
      <visualize>true</visualize>
    </sensor>
  </gazebo>

  <link name="eyecam_link"><xacro:tiny_inertial m="0.05"/></link>
  <joint name="eyecam_joint" type="fixed">
    <parent link="base_link"/>
    <child link="eyecam_link"/>
    <origin xyz="0.366 0 0.67"/>
  </joint>

  <link name="3dcam_link"><xacro:tiny_inertial m="0.10"/></link>
  <joint name="3dcam_joint" type="fixed">
    <parent link="base_link"/>
    <child link="3dcam_link"/>
    <origin xyz="0.206 0 0.255"/>
  </joint>

  <!-- ===================================================== -->
  <!-- Gazebo Diff Drive (gz-sim, Jazzy)                     -->
  <!-- ===================================================== -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
      <left_joint>drivewhl_l_joint</left_joint>
      <right_joint>drivewhl_r_joint</right_joint>

      <wheel_separation>${track}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <max_linear_velocity>1.4</max_linear_velocity>
      <max_angular_velocity>0.63</max_angular_velocity>

      <!-- CHANGED: lower accel also caps braking decel (less "nose dive") -->
      <max_linear_acceleration>0.4</max_linear_acceleration>

      <max_angular_acceleration>0.4</max_angular_acceleration>

      <topic>/cmd_vel</topic>
      <odom_topic>/odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
    </plugin>
  </gazebo>

</robot>
