<?xml version="1.0"?>
<robot name="k9_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- ===================================================== -->
  <!-- To generate SDF for Gazebo Sim                        -->
  <!-- ros2 run xacro xacro k9.urdf.xacro > k9.urdf          -->
  <!-- gz sdf -p k9.urdf > k9_raw.sdf                        -->
  <!-- python3 patch_friction.py k9_raw.sdf k9_robot.sdf     -->
  <!-- ===================================================== -->

  <!-- ===================================================== -->
  <!-- Materials                                             -->
  <!-- ===================================================== -->
  <material name="K9_grey">
    <color rgba="0.25 0.25 0.25 1.0"/>
  </material>

  <material name="wheel_grey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <material name="k9_ear_emissive">
  <color rgba="0 0 0 1"/>
  </material>

  <material name="k9_beam_material">
    <color rgba="0 1 0 1"/>
  </material>

  <!-- ===================================================== -->
  <!-- Constants                                             -->
  <!-- ===================================================== -->
  <xacro:property name="wheel_radius" value="0.0694"/>
  <xacro:property name="wheel_width"  value="0.025"/>
  <xacro:property name="track"         value="0.2022"/>

  <!-- Ball caster -->
  <xacro:property name="ball_radius"  value="0.04"/>
  <xacro:property name="ball_x"       value="-0.30"/>

  
  <!-- ===================================================== -->
  <!-- Helper macros                                         -->
  <!-- ===================================================== -->
  <xacro:macro name="tiny_inertial" params="m">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${m}"/>
      <inertia
        ixx="1e-4" ixy="0" ixz="0"
        iyy="1e-4" iyz="0"
        izz="1e-4"/>
    </inertial>
  </xacro:macro>

  <!-- ===================================================== -->
  <!-- IMU (Gazebo Sim) helper macro                          -->
  <!-- ===================================================== -->
  <xacro:macro name="k9_add_imu" params="
    parent_link
    imu_link:=imu_link
    xyz:='0 0 0'
    rpy:='0 0 0'
    update_rate:=200
    accel_noise:=0.02
    gyro_noise:=0.002
    accel_bias:=0.0
    gyro_bias:=0.0
  ">

    <!-- A tiny link to carry the IMU sensor -->
    <link name="${imu_link}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.02"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
      </inertial>
    </link>

    <joint name="${imu_link}_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${imu_link}"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

    <!-- Gazebo Sim sensor definition -->
    <gazebo reference="${imu_link}">
      <sensor name="${imu_link}_sensor" type="imu">
        <topic>/k9/imu</topic>
        <always_on>true</always_on>
        <visualize>false</visualize>
        <update_rate>${update_rate}</update_rate>

        <!-- Noise model (tune these to feel like your BNO080) -->
        <imu>
          <angular_velocity>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>${gyro_noise}</stddev>
                <bias_mean>${gyro_bias}</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>${gyro_noise}</stddev>
                <bias_mean>${gyro_bias}</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>${gyro_noise}</stddev>
                <bias_mean>${gyro_bias}</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </z>
          </angular_velocity>

          <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>${accel_noise}</stddev>
                <bias_mean>${accel_bias}</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>${accel_noise}</stddev>
                <bias_mean>${accel_bias}</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>${accel_noise}</stddev>
                <bias_mean>${accel_bias}</bias_mean>
                <bias_stddev>0.0</bias_stddev>
              </noise>
            </z>
          </linear_acceleration>
        </imu>

      </sensor>
    </gazebo>

  </xacro:macro>

  <!-- ===================================================== -->
  <!-- OAK-D Lite-ish RGBD -> PointCloud (Gazebo Sim)         -->
  <!-- ===================================================== -->
  <xacro:macro name="k9_add_oakd_pointcloud" params="
    parent_link
    oak_link:=oakd_link
    xyz:='0 0 0'
    rpy:='0 0 0'
    width:=640
    height:=400
    update_rate:=30
    hfov:=1.3962634
    near:=0.20
    far:=8.0
    depth_noise_stddev:=0.01
    gz_topic:='/oak'
    frame_id:='oak_depth_frame'">

    <!-- A tiny link to carry the camera sensor -->
    <link name="${oak_link}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.05"/>
        <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
      </inertial>
    </link>

    <joint name="${oak_link}_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${oak_link}"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

    <gazebo reference="${oak_link}">
      <sensor name="${oak_link}_rgbd" type="rgbd_camera">
        <always_on>true</always_on>
        <visualize>false</visualize>
        <update_rate>${update_rate}</update_rate>
        <topic>${gz_topic}</topic>
        <camera>
          <horizontal_fov>${hfov}</horizontal_fov>
          <image>
            <width>${width}</width>
            <height>${height}</height>
          </image>
          <clip>
            <near>${near}</near>
            <far>${far}</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.003</stddev>
          </noise>
        </camera>
      </sensor>
    </gazebo>

  </xacro:macro>

  <!-- ===================================================== -->
  <!-- Frames                                                -->
  <!-- ===================================================== -->
  <link name="base_footprint"/>

  <!-- ===================================================== -->
  <!-- Base / chassis                                        -->
  <!-- ===================================================== -->
  <link name="base_link">

    <!-- Visual -->
    <visual>
      <origin xyz="-0.5 1.905 ${-wheel_radius}" rpy="0 0 ${pi}"/>
      <geometry>
        <mesh filename="file:///home/hopkira/Documents/GitHub/k9-gazebo/src/k9_description/urdf/k9.stl"
              scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="K9_grey"/>
    </visual>

    <!-- Collision -->
    <collision>
      <origin xyz="0.0 0.0 0.44"/>
      <geometry>
        <box size="1.05 0.49 0.74"/>
      </geometry>
    </collision>

    <!-- Inertia: main shell + structure -->
    <!-- CHANGED: lower + slightly rear-shift COM, and increase pitch inertia (iyy) -->
    <inertial>
      <!-- was: -0.02 0 0.20 -->
      <origin xyz="-0.06 0 0.16"/>
      <mass value="19.0"/>
      <inertia
        ixx="0.80"
        ixy="0" ixz="0"
        iyy="2.40"
        iyz="0"
        izz="1.70"/>
    </inertial>

  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}"/>
  </joint>

  <!-- ===================================================== -->
  <!-- Battery (low + central)                               -->
  <!-- ===================================================== -->
  <link name="battery_link">
    <collision>
      <geometry>
        <box size="0.25 0.20 0.25"/>
      </geometry>
    </collision>
    <xacro:tiny_inertial m="5.0"/>
  </link>

  <joint name="battery_joint" type="fixed">
    <parent link="base_link"/>
    <child link="battery_link"/>
    <origin xyz="0 0 0.18"/>
  </joint>

  <!-- ===================================================== -->
  <!-- Motors                                                -->
  <!-- ===================================================== -->
  <link name="motors_link">
    <collision>
      <geometry>
        <box size="0.20 0.20 0.10"/>
      </geometry>
    </collision>
    <xacro:tiny_inertial m="3.0"/>
  </link>

  <joint name="motors_joint" type="fixed">
    <parent link="base_link"/>
    <child link="motors_link"/>
    <origin xyz="0 0 0.10"/>
  </joint>

  <!-- ===================================================== -->
  <!-- Drive wheels                                          -->
  <!-- ===================================================== -->
  <xacro:macro name="drive_wheel" params="name y">
    <link name="${name}_link">
      <visual>
        <origin rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="wheel_grey"/>
      </visual>
      <collision>
        <origin rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <inertia
          ixx="0.002" ixy="0" ixz="0"
          iyy="0.002" iyz="0"
          izz="0.004"/>
      </inertial>
    </link>

    <gazebo reference="${name}_link">
      <mu1>0.9</mu1>
      <mu2>0.7</mu2>
    </gazebo>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="0 ${y} 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.05"/>
    </joint>
  </xacro:macro>

  <xacro:drive_wheel name="drivewhl_l" y="${ track/2}"/>
  <xacro:drive_wheel name="drivewhl_r" y="${-track/2}"/>

  <!-- ===================================================== -->
  <!-- Ball caster (4 cm sphere)                              -->
  <!-- ===================================================== -->
  <link name="ball_caster_link">
    <visual>
      <geometry>
        <sphere radius="${ball_radius}"/>
      </geometry>
      <material name="wheel_grey"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${ball_radius}"/>
      </geometry>
    </collision>
    <xacro:tiny_inertial m="0.5"/>
  </link>

  <gazebo reference="ball_caster_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
  </gazebo>

  <joint name="ball_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="ball_caster_link"/>
    <origin xyz="${ball_x} 0 ${ball_radius - wheel_radius}"/>
  </joint>

  <!-- ===================================================== -->
  <!-- Sensors                                               -->
  <!-- ===================================================== -->
  <!-- started at 0.565 raised by 20 cm to clear body       -->
  
  <link name="base_laser"><xacro:tiny_inertial m="0.05"/></link>
  <joint name="base_laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_laser"/>
    <origin xyz="-0.112 0 0.53" rpy ="0 0 0"/>
  </joint>
  <gazebo reference="base_laser">
    <sensor name="ld06_lidar" type="gpu_lidar">
      <update_rate>10</update_rate>
      <always_on>true</always_on>
      <topic>/ld06/scan</topic>
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.02</min>
          <max>12.0</max>
        </range>
      </lidar>
    </sensor>
  </gazebo>

  <link name="eyecam_link"><xacro:tiny_inertial m="0.05"/></link>
  <joint name="eyecam_joint" type="fixed">
    <parent link="base_link"/>
    <child link="eyecam_link"/>
    <origin xyz="0.366 0 0.67"/>
  </joint>

  <link name="3dcam_link"><xacro:tiny_inertial m="0.10"/></link>
  <joint name="3dcam_joint" type="fixed">
    <parent link="base_link"/>
    <child link="3dcam_link"/>
    <origin xyz="0.206 0 0.255"/>
  </joint>

  <!-- ******************** LEFT EAR ****************************** -->

  <link name="l_ear_link">
    <!-- Visual (for Gazebo visualisation) -->
    <visual name="l_ear_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.02 0.03"/>
      </geometry>
      <material name="k9_ear_emissive">
        <ambient>0 0 0 1</ambient>
        <diffuse>0 0 0 1</diffuse>
        <emissive>0 0 0 1</emissive> <!-- will be driven by Gazebo -->
      </material>
    </visual>
    <xacro:tiny_inertial m="0.05"/>
  </link>

  <gazebo reference="l_ear_link">
    <sensor name="l_ear_tof" type="gpu_lidar">
      <pose>0.0075 0 0 0 0 0</pose>
      <update_rate>30</update_rate>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <topic>/l_ear/scan</topic>
      <lidar>
        <scan>
          <horizontal>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.02</min>
          <max>2.0</max>
          <resolution>0.001</resolution>
        </range>
      </lidar>
    </sensor>
  </gazebo>

  <joint name="l_ear_joint" type="revolute">
    <parent link="base_link"/>
    <child link="l_ear_link"/>
    <origin xyz="0.165 0.04 0.74" rpy="0.0 0.25 0.0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.2" upper="0.6" effort="0.1" velocity="10"/>
    <dynamics friction="0.1" damping="0.1"/>
  </joint>

  <!-- ******************** RIGHT EAR ****************************** -->

  <link name="r_ear_link">

    <visual name="r_ear_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.02 0.03"/>
      </geometry>
      <material name="k9_ear_emissive">
        <ambient>0 0 0 1</ambient>
        <diffuse>0 0 0 1</diffuse>
        <emissive>0 0 0 1</emissive>
      </material>
    </visual>
    <xacro:tiny_inertial m="0.05"/>
  </link>

  <gazebo reference="r_ear_link">
    <sensor name="r_ear_tof" type="gpu_lidar">
      <pose>0.0075 0 0 0 0 0</pose>
      <update_rate>30</update_rate>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <topic>/r_ear/scan</topic>
      <lidar>
        <scan>
          <horizontal>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.02</min>
          <max>2.0</max>
          <resolution>0.001</resolution>
        </range>
      </lidar>
    </sensor>
  </gazebo>

  <joint name="r_ear_joint" type="revolute">
    <parent link="base_link"/>
    <child link="r_ear_link"/>
    <origin xyz="0.165 -0.04 0.74" rpy="0.0 0.25 0.0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.6" upper="0.2" effort="0.1" velocity="10"/>
    <dynamics friction="0.1" damping="0.1"/>
  </joint>

  <xacro:k9_add_imu 
    parent_link="base_link"
    imu_link="imu_link"
    xyz="0 0 0.16"
    rpy="0 0 0"
    update_rate="200"
    accel_noise="0.01"
    gyro_noise="0.001"/>

  <xacro:k9_add_oakd_pointcloud
    parent_link="base_link"
    oak_link="oakd_link"
    xyz="0.26 0 0.255"
    rpy="0 0 0"
    gz_topic="/oak"
    frame_id="oak_depth_frame"/>

  <!-- ===================================================== -->
  <!-- Gazebo Diff Drive (gz-sim, Jazzy)                     -->
  <!-- ===================================================== -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
      <left_joint>drivewhl_l_joint</left_joint>
      <right_joint>drivewhl_r_joint</right_joint>

      <wheel_separation>${track}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <max_linear_velocity>1.4</max_linear_velocity>
      <max_angular_velocity>0.63</max_angular_velocity>

      <!-- CHANGED: lower accel also caps braking decel (less "nose dive") -->
      <max_linear_acceleration>0.28</max_linear_acceleration>

      <max_angular_acceleration>0.21</max_angular_acceleration>

      <topic>/cmd_vel</topic>
      <odom_topic>/odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
    </plugin>
  </gazebo>

</robot>
