<?xml version="1.0" ?>
<robot name="k9_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!--COLOURS-->
  <material name="K9 grey">
    <color rgba="0.5 0.5 1.0 0.3" />
  </material>

    <material name="K9 mesh">
    <color rgba="0.7 0.7 0.8 1.0" />
  </material>

  <material name="wheel grey">
    <color rgba="0.7 0.7 0.7 1.0" />
  </material>

  <material name="collision red">
    <color rgba="1.0 0.1 0.1 0.3" />
  </material>

  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m x y z o_xyz o_rpy">
      <inertial>
          <mass value="${m}" />
          <origin xyz="${o_xyz}" rpy="${o_rpy}" />
          <inertia ixx="${(m/12) * (y*y + z*z)}" ixy="0" ixz="0"
                    iyy="${(m/12) * (x*x + z*z)}" iyz="0"
                    izz="${(m/12) * (x*x + y*y)}" />
      </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r l o_xyz o_rpy">
      <inertial>
          <mass value="${m}" />
          <origin xyz="${o_xyz}" rpy="${o_rpy}" />
          <inertia ixx="${(m/12) * (3*r*r + l*l)}" ixy="0" ixz="0"
                    iyy="${(m/12) * (3*r*r + l*l)}" iyz="0"
                    izz="${(m/2) * (r*r)}" />
      </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r o_xyz o_rpy">
      <inertial>
          <mass value="${m}" />
          <origin xyz="${o_xyz}" rpy="${o_rpy}" />
          <inertia ixx="${(2/5) * m * r * r}" ixy="0" ixz="0"
                    iyy="${(2/5) * m * r * r}" iyz="0"
                    izz="${(2/5) * m * r * r}" />
      </inertial>
  </xacro:macro>

  <!--BASE-->
  <xacro:property name="base_width" value="0.49"/>
  <xacro:property name="base_length" value="1.1"/>
  <xacro:property name="base_height" value="0.77"/>
  <xacro:property name="base_x_offset" value="-0.1"/>
  <xacro:property name="base_clearance" value="0.035"/>

    <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="${base_x_offset} 0 ${base_clearance+(base_height/2)}" rpy="0 0 ${pi}"/>
      <material name="collision red"/>
    </visual>    
    <collision>
      <origin xyz="-0.2 0.0 0.297" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.89 ${base_width} 0.52"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0.23 0.0 0.55" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.43 0.18 0.15"/>
      </geometry>
    </collision>    
    <collision>
      <origin xyz="0.15 0.0 0.65" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.2 0.18 0.1"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="40.0" x="${base_length*.8}" y="${base_width}" z="${base_height/2}" o_xyz="0 0 ${base_clearance+(base_height/4)}" o_rpy="0 0 0"/>
  </link>

  <!-- MESH -->
  <link name="mesh_link">
    <visual>
      <origin xyz="-0.58 1.905 0" rpy="0 0 ${pi}" />
      <geometry>
        <mesh filename="package://k9_description/urdf/k9.stl" scale = "0.01 0.01 0.01"/>
      </geometry>
    <material name="K9 mesh"/>
    </visual>
  </link>

  <joint name="base_mesh_joint" type="fixed">
    <parent link="base_link" />
    <child link="mesh_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>


  <!--DRIVE WHEELS-->
  <xacro:property name="wheel_radius" value="0.06939"/>
  <xacro:property name="wheel_width" value="0.014"/>
  <xacro:property name="wheel_gap" value="0.2022"/>

  <link name="l_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <material name="wheel grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="0.4" r="${wheel_radius}" l="${wheel_width}" o_xyz="0 0 0" o_rpy="${pi/2} 0 0"/>
  </link>

  <joint name="base_l_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="l_wheel_link"/>
    <origin xyz="0 ${wheel_gap/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="r_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <material name="wheel grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </collision>
    <xacro:cylinder_inertia m="0.4" r="${wheel_radius}" l="${wheel_width}" o_xyz="0 0 0" o_rpy="${pi/2} 0 0"/>
  </link>

  <joint name="base_r_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="r_wheel_link"/>
    <origin xyz="0 ${-wheel_gap/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!--BASE FOOTPRINT-->
  <link name="base_footprint">
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!--REAR CASTOR-->
  <xacro:property name="castor_x_offset" value="-0.298"/>
  <xacro:property name="castor_radius" value="0.02"/>

  <link name="castor_link">
    <visual>
      <geometry>
        <sphere radius="${castor_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="wheel grey"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${castor_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <xacro:sphere_inertia m="0.2" r="${castor_radius}" o_xyz ="0 0 0" o_rpy="0 0 0"/>
  </link>

 <joint name="castor_joint" type="fixed">
    <parent link="base_link" />
    <child link="castor_link"/>
    <origin xyz="${castor_x_offset} 0 ${castor_radius}" rpy="0 0 0"/>
  </joint>

  <!-- *********************** LIDAR ********************************  -->
  <link name="lidar_link"/>
  
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="-0.2	0.0	0.555" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- ******************** EYE CAMERA ******************************  -->
  <link name="eyecam_link"/>
 
  <joint name="eyecam_joint" type="fixed">
    <parent link="base_link"/>
    <child link="eyecam_link"/>
    <origin xyz="0.266 0.0 0.67" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- ******************** 3D CAMERA ******************************  -->
  <link name="3dcam_link"/>
  
  <joint name="3dcam_joint" type="fixed">
    <parent link="base_link"/>
    <child link="3dcam_link"/>
    <origin xyz="0.13 0.0 0.255" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- ******************** LEFT EAR ******************************  -->

  <link name="l_ear_link">    
    <visual>
      <geometry>
        <box size="0.015 0.02 0.03"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="wheel grey"/>
    </visual>    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.02 0.03"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.02 0.03"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.05" x="0.015" y="0.02" z="0.03" o_xyz="0 0 0" o_rpy="0 0 0"/>
  </link>

  <joint name="l_ear_joint" type="revolute">
    <parent link="base_link"/>
    <child link="l_ear_link"/>
    <origin xyz="0.165 0.04 0.74" rpy="0.0 0.25 0.0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.2" upper="0.6" effort="0.1" velocity="10"/>
    <dynamics friction="0.1" damping="0.1"/>
  </joint>

  <!-- ******************** RIGHT EAR ******************************  -->
  <link name="r_ear_link">
    <visual>
      <geometry>
        <box size="0.015 0.02 0.03"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="wheel grey"/>
    </visual>    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.02 0.03"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.02 0.03"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.05" x="0.015" y="0.02" z="0.03" o_xyz="0 0 0" o_rpy="0 0 0"/>
  </link> 

  <joint name="r_ear_joint" type="revolute">
    <parent link="base_link"/>
    <child link="r_ear_link"/>
    <origin xyz="0.165 -0.04 0.74" rpy="0.0 0.25 0.0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.6" upper="0.2" effort="0.1" velocity="10"/>
    <dynamics friction="0.1" damping="0.1"/>
  </joint>

  <gazebo reference="castor_link">
      <mu1 value="0.001" />
      <mu2 value="0.001" />
  </gazebo>

  <gazebo reference="r_wheel_link">
      <mu1 value="200" />
      <mu2 value="200" />
      <kp value="10000000.0"/>
      <kd value="1.0"/>
      <minDepth>0.01</minDepth>
  </gazebo>

  <gazebo reference="l_wheel_link">
      <mu1 value="200" />
      <mu2 value="200" />
      <kp value="10000000.0"/>
      <kd value="1.0"/>
      <minDepth>0.01</minDepth>
  </gazebo>

  <gazebo>
  <plugin 
      filename="gz-sim-diff-drive-system" 
      name="gz::sim::systems::DiffDrive">
      <left_joint>base_l_wheel_joint</left_joint>
      <right_joint>base_r_wheel_joint</right_joint>
      <wheel_separation>"${wheel_gap}"</wheel_separation>
      <wheel_radius>"${wheel_radius}"</wheel_radius>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
  </plugin>
  </gazebo>

  <gazebo>
  <plugin 
      filename="gz-sim-joint-state-publisher-system" 
      name="gz::sim::systems::JointStatePublisher">
      <joint_name>base_l_wheel_joint</joint_name>
      <joint_name>base_r_wheel_joint</joint_name>
      <joint_name>l_ear_joint</joint_name>
      <joint_name>r_ear_joint</joint_name>
  </plugin>
  </gazebo>

</robot>
